$(document).ready(function(){
    $(".brands-carousel").owlCarousel({
        responsiveClass:true,
        responsive:{
            0:{
                items:1,
            },
            768:{
                items:6,
            },
            992:{
                items:8,
            }
        }
    });
});